name: Build and deploy Node.js app to Azure Web App - insurance-estimate

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Zip backend directory
        run: |
          cd backend
          zip -r ../backend.zip .

      - name: Upload backend artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifact
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: backend-artifact
          path: .

      - name: Unzip backend artifact
        run: |
          unzip backend.zip -d backend

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "insurance-estimate"
          slot-name: "production"
          package: backend
